name: aimpostor
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  path: ^1.8.3
  image_picker: ^1.0.4
  http: ^1.1.0
  flutter_dotenv: ^5.1.0

  english_words: ^4.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true