// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjbGTEw8TiZpDd8XuG7PyTR1iKd_qrSm8',
    appId: '1:202387659163:web:055c707ac974449b25a93e',
    messagingSenderId: '202387659163',
    projectId: 'ai-mposter',
    authDomain: 'ai-mposter.firebaseapp.com',
    storageBucket: 'ai-mposter.firebasestorage.app',
    measurementId: 'G-Z2R5RS362E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG75gTeMFz6vnOIkyy_PPpx9JZCUL8TWQ',
    appId: '1:202387659163:android:6d415d73f048e95825a93e',
    messagingSenderId: '202387659163',
    projectId: 'ai-mposter',
    storageBucket: 'ai-mposter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoZAONI1VXKjGKasHkNNGhOmaya8tVI_A',
    appId: '1:202387659163:ios:ba523e89feb2aa8525a93e',
    messagingSenderId: '202387659163',
    projectId: 'ai-mposter',
    storageBucket: 'ai-mposter.firebasestorage.app',
    androidClientId: '202387659163-0am1t57kfq6cjmagoe1tg5bla2pa5mft.apps.googleusercontent.com',
    iosClientId: '202387659163-vd8j2s6tg6q53adpu7ac50hs87opduv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriwise',
  );
}
